version: "3.2"

services:
  neo4j:
    image: neo4j:4.2
    container_name: 'neo4j'
    restart: on-failure
    ports:
      - '7474:7474'
      - '7687:7687'
    environment: 
      - NEO4J_AUTH=neo4j/1234
    command: neo4j
  back-end:
    container_name: 'go'
    build: './back-end'
    ports:
      - '3001:3001'
    depends_on:
      - neo4j
    network_mode: host
  front-end:
    container_name: 'react'
    restart: on-failure
    build: './front-end'
    stdin_open: true
    environment: 
      - PORT=3000
    ports: 
      - "3000:3000"
    depends_on:
      - back-end
    network_mode: host
      
