version: "3.2"

services:
  neo4j:
    image: neo4j:4.0
    container_name: 'neo4j'
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/plugins:/plugins  
      - $HOME/neo4j/conf:/conf  
    environment: 
      - NEO4J_AUTH=neo4j/1234
    command: neo4j
  back-end:
    container_name: 'go'
    restart: unless-stopped
    build: './back-end'
    ports:
      - '3001:3001'
    depends_on:
      - neo4j
    network_mode: host
  front-end:
    container_name: 'react'
    restart: unless-stopped
    build: './front-end'
    stdin_open: true
    ports: 
      - 3000:3000
    depends_on:
      - back-end
    network_mode: host
      
